### ISSUE TITLE
This doesn't compile

### ISSUE THREAD

**Issue by XP-Fan** [19h/ftab-dump#1]
peter@peterpi:~ $ cargo install ftab-dump                                       

     Updating crates.io index                                                    

        Fetch [                                                       ]   0.00%  

   Installing ftab-dump v1.0.2                                                   

    Compiling libc v0.2.97                                                       

    Compiling bitflags v1.2.1                                                    

    Compiling unicode-width v0.1.8                                               

    Compiling ansi_term v0.11.0                                                  

     Building [                                                          ] 0/15  

    Compiling strsim v0.8.0                                                      

     Building [==>                                                       ] 1/15  

    Compiling vec_map v0.8.2                                                     

     Building [======>                                                   ] 2/15  

    Compiling byteorder v1.4.3                                                   

     Building [==========>                                               ] 3/15  

    Compiling textwrap v0.11.0                                                   

     Building [==============>                                           ] 4/15  

     Building [==================>                                       ] 5/15  

     Building [======================>                                   ] 6/15  

     Building [==========================>                               ] 7/15  

     Building [=============================>                            ] 8/15  

     Building [=================================>                        ] 9/15  

     Building [=====================================>                   ] 10/15  

     Building [========================================>                ] 11/15  

    Compiling atty v0.2.14                                                       

    Compiling clap v2.33.3                                                       

     Building [============================================>            ] 12/15  

     Building [================================================>        ] 13/15  

    Compiling ftab-dump v1.0.2                                                   

====>    ] 14
 error[E0658]: use of unstable library feature 'repeat_generic_slice': it's on st

 r, why not on slice?                                                            

  --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/ftab-dump-1.0.2

 /src/rkos_parser.rs:8:25                                                        

   |                                                                             

 8 |     let mut buf = [0u8].repeat(len);                                        

   |                         ^^^^^^                                              

   |                                                                             

   = note: for more information, see https://github.com/rust-lang/rust/issues/487

 84                                                                              

 error: aborting due to previous error                                           

 For more information about this error, try `rustc --explain E0658`.             

 error: failed to compile `ftab-dump v1.0.2`, intermediate artifacts can be found

  at `/tmp/cargo-installfPagi1`                                                  

 Caused by:                                                                      

   could not compile `ftab-dump`.                                                

 To learn more, run the command again with --verbose.                            

 peter@peterpi:~ $

**Comment by 19h** [comment]
You need to use Rust nightly.
