### ISSUE TITLE
encrypted content

### ISSUE THREAD

**Issue by Z000000** [19h/ftab-dump#2]
when i unpack the packages i got the encrypted content how i can get the plaintext content

**Comment by 19h** [comment]
What device and image?

**Comment by Z000000** [comment]
> What device and image?

https://www.theiphonewiki.com/wiki/OTA_Updates/AirPods_Pro



30.877000006000000.1075 | 3A283 | Harpsichord | 14 Sep 2020 | cc9847d7a89fffc28dc0eaae8178969cc05ea2b1.zip | 2,727,381

3A283  AssetData\Firmware.acsw\ftab.bin

**Comment by 19h** [comment]
This dumper works as expected (the encrypted file was dumped properly) and the decryption is out of scope. I‘ll check it out anyway and will let you know later.

**Comment by 19h** [comment]
Tip: since those updates contain firmware for every layer of the device, the decryption mechanism must be included in the last unencrypted update.

**Comment by 19h** [comment]
Neither the files in the 3A283 nor the 3E751 build are encrypted.

<img width="1582" alt="CleanShot 2021-08-02 at 15 06 43@2x" src="https://user-images.githubusercontent.com/280212/127866802-95233347-0c39-4844-ac1e-0fbaa712ccf6.png">

**Comment by 19h** [comment]
1. `ftab-dump ftab.bin`
2. open ftab_dump/rkos in Ghidra as ARM Cortex 32 bit little endian

**Comment by Z000000** [comment]
thank you very much
